CREATE database OpenMps;

CREATE TABLE `OpenMps`.`oid`
(
  `Id` Bigint NOT NULL AUTO_INCREMENT,
  `HerstellerName` TEXT NOT NULL,
  `OIDPrivateID` TEXT NOT NULL,
  `ProfileName` TEXT NOT NULL,
  `DeviceName` TEXT NOT NULL,
  `DeviceType` TEXT NOT NULL,
  `Manufacturer` TEXT NOT NULL,
  `Model` TEXT NOT NULL,
  `SerialNumber` TEXT NOT NULL,
  `MACAddress` TEXT NOT NULL,
  `IPAddresse` TEXT NOT NULL,
  `HostName` TEXT NOT NULL,
  `DescriptionLocation` TEXT NOT NULL,
  `AssetNumber` TEXT NOT NULL,
  `FirmwareVersion` TEXT NOT NULL,
  `PowerSleep1` TEXT NOT NULL,
  `PowerSleep2` TEXT NOT NULL,
  `TotalPages` TEXT NOT NULL,
  `TotalPagesMono` TEXT NOT NULL,
  `TotalPagesColor` TEXT NOT NULL,
  `TotalPagesDuplex` TEXT NOT NULL,
  `PrinterPages` TEXT NOT NULL,
  `PrinterPagesMono` TEXT NOT NULL,
  `PrinterPagesColor` TEXT NOT NULL,
  `PrinterPagesFullColor` TEXT NOT NULL,
  `PrinterPagesTwoColor` TEXT NOT NULL,
  `CopyPagesMono` TEXT NOT NULL,
  `CopyPagesColor` TEXT NOT NULL,
  `CopyPagesFullColor` TEXT NOT NULL,
  `CopyPagesTwoColor` TEXT NOT NULL,
  `CopyPagesSingleColor` TEXT NOT NULL,
  `FaxesSentFaxesReceived` TEXT NOT NULL,
  `ScansTotalScansTotalMono` TEXT NOT NULL,
  `ScansTotalColor` TEXT NOT NULL,
  `ScansCopyMono` TEXT NOT NULL,
  `ScansCopyColor` TEXT NOT NULL,
  `ScansEmail` TEXT NOT NULL,
  `ScansEmailMono` TEXT NOT NULL,
  `ScansNet` TEXT NOT NULL,
  `ScansNetMono` TEXT NOT NULL,
  `ScansNetColor` TEXT NOT NULL,
  `LargePagesMono` TEXT NOT NULL,
  `LargePagesFullColor` TEXT NOT NULL,
  `CoverageAverageBlack` TEXT NOT NULL,
  `CoverageAverageCyan` TEXT NOT NULL,
  `CoverageAverageMagenta` TEXT NOT NULL,
  `CoverageAverageYellow` TEXT NOT NULL,
  `BlackLevelMax` TEXT NOT NULL,
  `CyanLevelMax` TEXT NOT NULL,
  `MagentaLevelMax` TEXT NOT NULL,
  `YellowLevelMax` TEXT NOT NULL,
  `BlackLevel` TEXT NOT NULL,
  `CyanLevel` TEXT NOT NULL,
  `MagentaLevel` TEXT NOT NULL,
  `YellowLevel` TEXT NOT NULL,
  PRIMARY KEY (`Id`)
);