CREATE database OpenMPS;
use OpenMPS;


CREATE TABLE `Directory` (
  `DKey` varchar(400) NOT NULL,
  `DValue` varchar(400) NOT NULL,
  PRIMARY KEY (`DKey`,`DValue`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Oid` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `VendorName` text NOT NULL,
  `OidPrivateId` text NOT NULL,
  `ProfileName` text NOT NULL,
  `DeviceName` text NOT NULL,
  `DeviceType` text NOT NULL,
  `Manufacturer` text NOT NULL,
  `Model` text NOT NULL,
  `SerialNumber` text NOT NULL,
  `MacAddress` text NOT NULL,
  `IpAddress` text NOT NULL,
  `HostName` text NOT NULL,
  `DescriptionLocation` text NOT NULL,
  `AssetNumber` text NOT NULL,
  `FirmwareVersion` text NOT NULL,
  `PowerSleep1` text NOT NULL,
  `PowerSleep2` text NOT NULL,
  `TotalPages` text NOT NULL,
  `TotalPagesMono` text NOT NULL,
  `TotalPagesColor` text NOT NULL,
  `TotalPagesDuplex` text NOT NULL,
  `PrinterPages` text NOT NULL,
  `PrinterPagesMono` text NOT NULL,
  `PrinterPagesColor` text NOT NULL,
  `PrinterPagesFullColor` text NOT NULL,
  `PrinterPagesTwoColor` text NOT NULL,
  `CopyPagesMono` text NOT NULL,
  `CopyPagesColor` text NOT NULL,
  `CopyPagesFullColor` text NOT NULL,
  `CopyPagesTwoColor` text NOT NULL,
  `CopyPagesSingleColor` text NOT NULL,
  `FaxesSentFaxesReceived` text NOT NULL,
  `ScansTotalScansTotalMono` text NOT NULL,
  `ScansTotalColor` text NOT NULL,
  `ScansCopyMono` text NOT NULL,
  `ScansCopyColor` text NOT NULL,
  `ScansEmail` text NOT NULL,
  `ScansEmailMono` text NOT NULL,
  `ScansNet` text NOT NULL,
  `ScansNetMono` text NOT NULL,
  `ScansNetColor` text NOT NULL,
  `LargePagesMono` text NOT NULL,
  `LargePagesFullColor` text NOT NULL,
  `CoverageAverageBlack` text NOT NULL,
  `CoverageAverageCyan` text NOT NULL,
  `CoverageAverageMagenta` text NOT NULL,
  `CoverageAverageYellow` text NOT NULL,
  `BlackLevelMax` text NOT NULL,
  `CyanLevelMax` text NOT NULL,
  `MagentaLevelMax` text NOT NULL,
  `YellowLevelMax` text NOT NULL,
  `BlackLevel` text NOT NULL,
  `CyanLevel` text NOT NULL,
  `MagentaLevel` text NOT NULL,
  `YellowLevel` text NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `OidData` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `customerRef` varchar(300) DEFAULT NULL,
  `VendorName` varchar(300) NOT NULL DEFAULT '',
  `Model` varchar(300) NOT NULL DEFAULT '',
  `SerialNumber` varchar(300) NOT NULL DEFAULT '',
  `MacAddress` varchar(300) NOT NULL DEFAULT '',
  `IpAddress` varchar(300) NOT NULL DEFAULT '',
  `HostName` varchar(300) NOT NULL DEFAULT '',
  `DescriptionLocation` varchar(300) NOT NULL DEFAULT '',
  `AssetNumber` varchar(300) NOT NULL DEFAULT '',
  `FirmwareVersion` varchar(300) NOT NULL DEFAULT '',
  `PowerSleep1` varchar(300) NOT NULL DEFAULT '',
  `PowerSleep2` varchar(300) NOT NULL DEFAULT '',
  `ProfileName` varchar(300) NOT NULL DEFAULT '',
  `DeviceName` varchar(300) NOT NULL DEFAULT '',
  `DeviceType` varchar(300) NOT NULL DEFAULT '',
  `Manufacturer` varchar(300) NOT NULL DEFAULT '',
  `TotalPages` bigint(20) NOT NULL DEFAULT '0',
  `TotalPagesMono` bigint(20) NOT NULL DEFAULT '0',
  `TotalPagesColor` bigint(20) NOT NULL DEFAULT '0',
  `TotalPagesDuplex` bigint(20) NOT NULL DEFAULT '0',
  `PrinterPages` bigint(20) NOT NULL DEFAULT '0',
  `PrinterPagesMono` bigint(20) NOT NULL DEFAULT '0',
  `PrinterPagesColor` bigint(20) NOT NULL DEFAULT '0',
  `PrinterPagesFullColor` bigint(20) NOT NULL DEFAULT '0',
  `PrinterPagesTwoColor` bigint(20) NOT NULL DEFAULT '0',
  `CopyPagesMono` bigint(20) NOT NULL DEFAULT '0',
  `CopyPagesColor` bigint(20) NOT NULL DEFAULT '0',
  `CopyPagesFullColor` bigint(20) NOT NULL DEFAULT '0',
  `CopyPagesTwoColor` bigint(20) NOT NULL DEFAULT '0',
  `CopyPagesSingleColor` bigint(20) NOT NULL DEFAULT '0',
  `FaxesSentFaxesReceived` bigint(20) NOT NULL DEFAULT '0',
  `ScansTotalScansTotalMono` bigint(20) NOT NULL DEFAULT '0',
  `ScansTotalColor` bigint(20) NOT NULL DEFAULT '0',
  `ScansCopyMono` bigint(20) NOT NULL DEFAULT '0',
  `ScansCopyColor` bigint(20) NOT NULL DEFAULT '0',
  `ScansEmail` bigint(20) NOT NULL DEFAULT '0',
  `ScansEmailMono` bigint(20) NOT NULL DEFAULT '0',
  `ScansNet` bigint(20) NOT NULL DEFAULT '0',
  `ScansNetMono` bigint(20) NOT NULL DEFAULT '0',
  `ScansNetColor` bigint(20) NOT NULL DEFAULT '0',
  `LargePagesMono` bigint(20) NOT NULL DEFAULT '0',
  `LargePagesFullColor` bigint(20) NOT NULL DEFAULT '0',
  `CoverageAverageBlack` bigint(20) NOT NULL DEFAULT '0',
  `CoverageAverageCyan` bigint(20) NOT NULL DEFAULT '0',
  `CoverageAverageMagenta` bigint(20) NOT NULL DEFAULT '0',
  `CoverageAverageYellow` bigint(20) NOT NULL DEFAULT '0',
  `BlackLevelMax` bigint(20) NOT NULL DEFAULT '0',
  `CyanLevelMax` bigint(20) NOT NULL DEFAULT '0',
  `MagentaLevelMax` bigint(20) NOT NULL DEFAULT '0',
  `YellowLevelMax` bigint(20) NOT NULL DEFAULT '0',
  `BlackLevel` bigint(20) NOT NULL DEFAULT '0',
  `CyanLevel` bigint(20) NOT NULL DEFAULT '0',
  `MagentaLevel` bigint(20) NOT NULL DEFAULT '0',
  `YellowLevel` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

CREATE TABLE `ServerLog` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `SocketId` varchar(100) DEFAULT NULL,
  `Message` text NOT NULL,
  `DateOfIncident` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=latin1;
